# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-04 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.TextField(default=''),
        ),
    ]
