# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-04 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.TextField(default=''),
        ),
    ]
