# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-11 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20181104_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
